name: Build iOS

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13'
    - name: Install Global Dependencies
      run: npm install -g @ionic/cli
    - name: Install Project Dependencies
      run: npm ci --legacy-peer-deps
    - name: Install CocoaPods
      run: sudo gem install cocoapods
    - name: Prepare iOS Project
      run: |
        cd ios/App
        npm install --legacy-peer-deps
        pod install
    - name: Build iOS
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $PWD/build/App.xcarchive
    - name: Export IPA
      run: |
        cd ios/App
        xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportPath $PWD/build -exportOptionsPlist ExportOptions.plist
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ios/App/build/App.ipa
